### ISSUE TITLE
Importing data issues

### ISSUE THREAD

**Issue by rgandhim** [ErasmusOIC/SMoLR#13]
Dear @JASlotman ,

I successfully installed SMoLR but I am not able to import my big thunderstorm .csv file for selecting ROIs but your publications says I can. There is no specific guidelines on how to do all that ?

Could you help me out here?

Thanks !

best,
Roja

**Comment by JASlotman** [comment]
Dear @rgandhim ,

First of all we dont use thunderstorm regularly so things are not often tested, if you run into something please let us know so we can adapt our code.

To import thunderstorm data you should use the SMOLR_IMPORT function:

For a single channel storm dataset it should be something like this:
data <- SMOLR_IMPORT(folder = "C:/whereveryourdatais/", profile ="thunderstorm")

Then subsequently the data can be visualized using 

name <- SMOLR(data)
plot(name)

or 

name <- SMOLR_KDE(data)
name <- SMOLR_DBSCAN(data)

for clustering.

Note that loading large datasets might take quite some time. 

I hope this works for you if not please e-mail me a j.slotman@erasmusmc.nl so we can maybe setup an online meeting where I can help you further.

Kind regards,

PS. we are working on a faster import function if you email me I can also share those scripts with you.

**Comment by JASlotman** [comment]
For other guidelines on usage also see: https://htmlpreview.github.io/?https://github.com/ErasmusOIC/SMoLR_data/blob/master/SMoLR.html

**Comment by rgandhim** [comment]
Thanks. I have sent you an email with the issues. :)

**Comment by maartenpaul** [comment]
Hi @rgandhim ,

I would like to add here that for drawing ROI's I would recommend using Fiji/ThunderSTORM. Drawing ROI's in R is difficult because rendering big images is not really efficient. We do have a function to apply ROI's (.roi/.zip) drawn in Fiji to a localization file, which is imported into SMoLR, see `IJROI_subset` . If you render an STORM image in ThunderSTORM with a defined pixel size and you draw the ROI's with the ROIManager they can be imported and processed in R. 

Please contact us if you have any questions!

Best regards, Maarten
